### ISSUE TITLE
Unable to get ROS2 Launch headless

### ISSUE THREAD

**Issue by wegunterjr** [MRPT/mvsim#54]
I tried with the included examples in mvsim after installing using:
`sudo apt install ros-$ROS_DISTRO-mvsim   `

But when i try to launch headless, the GUI and RVIZ still launch.
`ros2 launch mvsim demo_1robot.launch.py   --headless:=True`

**Comment by jlblancoc** [comment]
Oh, that's because that particular launch file was not prepared for that argument. 

It's now, after commit https://github.com/MRPT/mvsim/commit/dd2c8d59a488e1ca05e2a4338629f9270837ce6c

So you can either clone the repo, or just download [this file](https://github.com/MRPT/mvsim/blob/develop/mvsim_tutorial/demo_1robot.launch.py) anywhere in your disk, and run it with:

    cd /path/to/donwloaded_file/
    ros2 launch ./demo_1robot.launch.py headless:=True use_rviz:=False
