### ISSUE TITLE
Does it have GPU support? How could I enable it?

### ISSUE THREAD

**Issue by racarla96** [MRPT/mvsim#60]
Thank you for your simulator, it looks great and greatly simplifies the process of simulating a mobile robot. I watched your ROSCON video.

I want to know if the simulation has GPU support? I have installed the ROS package directly from apt and also compiled the simulator and I don't see the GPU being used, is there anything I should be aware of?

**Comment by jlblancoc** [comment]
Yes, it uses GPU already... if your system has opengl libraries suitable for your GPU. You can run: 

    glxinfo | grep OpenGL

and if it shows "NVidia", it should be already using hardware acceleration. 

I spent a few minutes looking for a way to monitoring how much a given OpenGL app is using the GPU but it seems there is no such tool. nvidia-smi only shows apps using the GPU for computing (CUDA). Since MVSim uses GPU via OpenGL, it will not be listed there...

**Comment by rafacastalla** [comment]
Thanks for your reply. I confirm that it works.

On the remote computer I was testing I have an AMD processor without integrated graphics and an NVIDIA, here I connect with XRDP, and I still don't know why OpenGL doesn't work correctly, I don't know how to configure it properly. (/etc/X11/)

But on my laptop with Ubuntu 22 and ROS 2, with an AMD with integrated graphics and NVIDIA it works correctly even with the integrated graphics of the processor, very fluid, it has really surprised me.

Again, thank you very much!

**Comment by racarla96** [comment]
Thanks for your reply. I confirm that it works.

On the remote computer I was testing I have an AMD processor without integrated graphics and an NVIDIA, here I connect with XRDP, and I still don't know why OpenGL doesn't work correctly, I don't know how to configure it properly. (/etc/X11/)

But on my laptop with Ubuntu 22 and ROS 2, with an AMD with integrated graphics and NVIDIA it works correctly even with the integrated graphics of the processor, very fluid, it has really surprised me.

Again, thank you very much!
